// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using namera_API.Data;

#nullable disable

namespace namera_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721023000_AddOrderItemCustomizationSnapshot")]
    partial class AddOrderItemCustomizationSnapshot
    {
    }
}
